### ISSUE TITLE
The oneops-admin gem should be in rubygems.org

### ISSUE THREAD

**Issue by bbourqu** [oneops/oneops-admin#53]
When doing custom builds or running through Continuous Integration systems like Travis, the systems read the gemspec file and try to download the gem during build.  This of course results in a error.  I think we should place the gem in rubygems as is a standard practice.

**Comment by mosabua** [comment]
I tend to agree.. the problem is that to some extend this applies to all our binaries and our release process and install process does not work with binaries at all. It is based on the github release tags mostly. Refactoring this to include binary creation and publishing is a big task. But maybe starting with this gem would be a good testbed. Wdyt @jvanzyl @vitaliyzinchenko ?

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
